version: '3.8'

services:

  server:

    build: ./api
    image: hn_server
    container_name: server

    depends_on:
      - database
      
    ports:
      - 8081:8081

    networks:
      - hn_network

  database:

    image: mongo
    container_name: database

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

    ports:
      - 27017:27017

    volumes:
      - ./db:/data/db

    networks:
      - hn_network

networks:

  hn_network:

    name: hn_network
    driver: bridge

volumes:

  hackervolume:
